BPI-776: changed confusing references of {core_id} and {tenant_id} to…
rackerlabs/docs-dedicated-networking pull request #36
Opened 2017-06-19 18:34 UTC by scotchneat

… {device_id} and {account_id} respectively since this is not a traditional cloud api.

2017-06-19 18:34 UTC, rackernexus commented
:mag_right: [Preview](https://staging.developer.rackspace.com/build-fd9b7bb8a7/docs/dedicated-load-balancers/v2/)

2017-06-19 18:40 UTC, rackernexus commented
:mag_right: [Preview](https://staging.developer.rackspace.com/build-af2cda767d/docs/dedicated-load-balancers/v2/)

2017-06-20 15:39 UTC, rajeevkct requested changes

2017-06-20 15:39 UTC, rajeevkct commented on load-balancer/api-docs/common-gs/auth-using-curl.rst
> +      $ export ACCOUNT_ID="account-id"
Line 67 says  tenant_id is the account number, i think we  can keep it as tenant_id here.

2017-07-06 19:21 UTC, rackernexus commented
:mag_right: [Preview](https://staging.developer.rackspace.com/build-258a0e82f7/docs/dedicated-load-balancers/v2/)

2017-07-06 19:22 UTC, scotchneat commented on load-balancer/api-docs/common-gs/auth-using-curl.rst
> +      $ export ACCOUNT_ID="account-id"
addressed these concerns and reverted the name to tenant

2017-07-07 13:27 UTC, cyrichardson approved these changes
From a copy edit perspective, LGTM. Thanks! Probably need a subject matter expert to do a technical review. I see you have requested one. Yay!

2017-07-11 14:43 UTC, rajeevkct approved these changes

2017-07-11 15:00 UTC, ramanbhati commented
Merging.

2017-07-11 15:00 UTC, merged